

curl -O http://sep.stanford.edu/sep/prof/beiLib/Cakefile.dir
curl -O http://sep.stanford.edu/sep/prof/beiLib/Makefile
curl -O http://sep.stanford.edu/sep/prof/beiLib/Makefile.dir
curl -O http://sep.stanford.edu/sep/prof/beiLib/OLDcakefile
curl -O http://sep.stanford.edu/sep/prof/beiLib/SGI64/
curl -O http://sep.stanford.edu/sep/prof/beiLib/aamig.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/adjnull.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/adjnull.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/bei.pc
curl -O http://sep.stanford.edu/sep/prof/beiLib/boxconv.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/boxconv.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/boxmo.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/boxmo.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/cary2
curl -O http://sep.stanford.edu/sep/prof/beiLib/causint.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/causint.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/causint2.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/causint2.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/contran.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/contran.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/cosmig.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/cosmig.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ctris.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ctris.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/diag.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/diag.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/dmokirch.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/dmokirch.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/doubint.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/doubint.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/dpbin2.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/dpbin2.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/eiktau.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/eiktau.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/flathyp.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/flathyp.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft.output
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft1axe.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft1axe.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft1axis.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft1axis.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft2axis.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft2axis.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft3D.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ft3D.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/fth.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/fth.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ftu.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ftu.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/gazadj.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/gazadj.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/halfdifa.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/halfdifa.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ident.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ident.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/igrad1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/igrad1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/junk
curl -O http://sep.stanford.edu/sep/prof/beiLib/kdmoslow.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/kdmoslow.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/kirchfast.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/kirchfast.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/kirchslow.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/kirchslow.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/lint1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/lint1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/lmo.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/lmo.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/matmul.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/matmul.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/matmult.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/matmult.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/mutter.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/mutter.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/mutter1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/mutter1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/nmo0.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/nmo0.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/nmo1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/nmo1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/null.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/null.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/pad2.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/pad2.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/phasemig.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/phasemig.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/phasemod.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/phasemod.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/quantile.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/quantile.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/rand01.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/rand01.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/rms2int.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/rms2int.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/rtris.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/rtris.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/ruffen1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/ruffen1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/scale.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/scale.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/simpleft.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/simpleft.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/slowfit.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/slowfit.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/spot0.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/spot0.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/spot1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/spot1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/spotw.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/spotw.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/stack0.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/stack0.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/stack1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/stack1.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/stoltmig.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/stoltmig.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/stoltmod.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/stoltmod.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/synmarine.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/synmarine.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/triangle.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/triangle.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/triangle2.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/triangle2.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/trimo.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/trimo.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/tristack.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/tristack.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/velsimp.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/velsimp.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/veltran.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/veltran.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/vint2rms.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/vint2rms.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/wavemovie.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/wavemovie.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/work.pc
curl -O http://sep.stanford.edu/sep/prof/beiLib/work.pcl
curl -O http://sep.stanford.edu/sep/prof/beiLib/zero.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/zero.stb
curl -O http://sep.stanford.edu/sep/prof/beiLib/zpad1.rt
curl -O http://sep.stanford.edu/sep/prof/beiLib/zpad1.stb